In [2]:
import os
import pickle
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [3]:
# Load the dataset
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# Preprocess the data
# Drop irrelevant columns

data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
# Encode categorical variables
label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])

In [6]:
# One Hot Encoding for Geography
data['Geography'].unique()

from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse_output=False)

geo_encoder = onehot_encoder.fit_transform(data[['Geography']])

In [7]:
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
geo_encoded = pd.DataFrame(geo_encoder, columns = onehot_encoder.get_feature_names_out(['Geography']))

In [9]:
geo_encoded

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
# Combine one hot encoded columns with the original dataframe
data = pd.concat([data.drop('Geography', axis = 1), geo_encoded], axis = 1)

In [11]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [13]:
# Save the encoders and scalers
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(label_encoder, file)

# Save the onehot encoder
with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(onehot_encoder, file)

In [12]:
# Divide the dataset into independent and dependent features
X = data.drop('EstimatedSalary', axis = 1)
y = data['EstimatedSalary']

In [14]:
# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [15]:
# Scale these features
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [16]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

# ANN Regression Problem Statement

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Build our ANN Model
model = Sequential([
    Dense(64, activation='relu', input_shape = (x_train.shape[1],)), # First hidden layer which is connected with input layer
    Dense(32, activation='relu'),
    Dense(1) #Output
])

# Compile the model
model.compile(optimizer = 'adam', loss = 'mean_absolute_error', metrics = ['mae'])

model.summary()

WARNING:tensorflow:From d:\Udemy\Gen AI\Projects\ANN Classification\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From d:\Udemy\Gen AI\Projects\ANN Classification\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From d:\Udemy\Gen AI\Projects\ANN Classification\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
# Setup the tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "regression/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir = log_dir, histogram_freq = 1)

In [19]:
# Setup Early Stopping
early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 10, restore_best_weights = True)

In [20]:
# Train the model
history = model.fit(
    x_train, y_train, validation_data = (x_test, y_test), epochs = 100,
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\Udemy\Gen AI\Projects\ANN Classification\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\Udemy\Gen AI\Projects\ANN Classification\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 4ms/step - loss: 100369.3125 - mae: 100369.3125 - val_loss: 98488.6562 - val_mae: 98488.6562
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99541.2891 - mae: 99541.2891 - val_loss: 96824.9922 - val_mae: 96824.9922
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 96665.9688 - mae: 96665.9688 - val_loss: 92629.8516 - val_mae: 92629.8516
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 91040.0156 - mae: 91040.0156 - val_loss: 85674.5469 - val_mae: 85674.5469
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 82969.6719 - mae: 82969.6719 - val_loss: 76975.3047 - val_mae: 76975.3047
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 73785.5625 - mae: 73785.5625 - val_loss: 68100.6406 - val_mae: 68100.6406
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 65021.9648 - mae: 65021.9648 - val_loss: 60476.3516 - val_mae: 60476.3516
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 58205.5703 - mae: 58205.5703 - val_loss: 55230.5273 - val_mae: 55230.5273
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 53982.5625 - mae: 53982.5625 - val_loss: 52449.7656 - val_mae: 52449.7656
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 51818.2578 - mae: 51818.2578 - val_loss: 51179.1523 - val_mae: 51179.1523
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 50859.9648 - mae: 50859.9648 - val_loss: 50749.3906 - val_mae: 50749.3906
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50486.1328 - mae: 50486.1328 - val_loss: 50636.1953 - val_mae: 50636.1953
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50339.2422 - mae: 50339.2422 - val_loss: 50574.8164 - val_mae: 50574.8164
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50250.1445 - mae: 50250.1445 - val_loss: 50529.1367 - val_mae: 50529.1367
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 50181.0234 - mae: 50181.0234 - val_loss: 50476.2852 - val_mae: 50476.2852
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50127.7852 - mae: 50127.7852 - val_loss: 50451.5938 - val_mae: 50451.5938
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50082.1133 - mae: 50082.1133 - val_loss: 50425.6562 - val_mae: 50425.6562
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50043.2578 - mae: 50043.2578 - val_loss: 50395.7695 - val_mae: 50395.7695
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 50002.6445 - mae: 50002.6445 - val_loss: 50378.3672 - val_mae: 50378.3672
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 49971.8867 - mae: 49971.8867 - val_loss: 50355.7617 - val_mae: 50355.7617
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49941.7422 - mae: 49941.7422 - val_loss: 50338.5273 - val_mae: 50338.5273
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 49915.1758 - mae: 49915.1758 - val_loss: 50320.1719 - val_mae: 50320.1719
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49888.8320 - mae: 49888.8320 - val_loss: 50307.6250 - val_mae: 50307.6250
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49865.1055 - mae: 49865.1055 - val_loss: 50300.8203 - val_mae: 50300.8203
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49839.1484 - mae: 49839.1484 - val_loss: 50283.6758 - val_mae: 50283.6758
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 49813.6523 - mae: 49813.6523 - val_loss: 50269.8633 - val_mae: 50269.8633
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49792.3594 - mae: 49792.3594 - val_loss: 50261.7969 - val_mae: 50261.7969
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 49773.8828 - mae: 49773.8828 - val_loss: 50259.7070 - val_mae: 50259.7070
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49757.7969 - mae: 49757.7969 - val_loss: 50251.0625 - val_mae: 50251.0625
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49740.0312 - mae: 49740.0312 - val_loss: 50246.1680 - val_mae: 50246.1680
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49722.5391 - mae: 49722.5391 - val_loss: 50238.5391 - val_mae: 50238.5391
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 49705.9336 - mae: 49705.9336 - val_loss: 50243.8438 - val_mae: 50243.8438
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49694.1484 - mae: 49694.1484 - val_loss: 50231.5586 - val_mae: 50231.5586
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49677.9648 - mae: 49677.9648 - val_loss: 50234.1484 - val_mae: 50234.1484
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49670.5508 - mae: 49670.5508 - val_loss: 50221.3789 - val_mae: 50221.3789
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 49652.1992 - mae: 49652.1992 - val_loss: 50219.3203 - val_mae: 50219.3203
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49644.7344 - mae: 49644.7344 - val_loss: 50231.1016 - val_mae: 50231.1016
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49633.8125 - mae: 49633.8125 - val_loss: 50222.6992 - val_mae: 50222.6992
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 49620.5117 - mae: 49620.5117 - val_loss: 50217.9805 - val_mae: 50217.9805
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 49608.6055 - mae: 49608.6055 - val_loss: 50217.0586 - val_mae: 50217.0586
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49598.9922 - mae: 49598.9922 - val_loss: 50211.8828 - val_mae: 50211.8828
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49591.2461 - mae: 49591.2461 - val_loss: 50226.4766 - val_mae: 50226.4766
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49579.4492 - mae: 49579.4492 - val_loss: 50217.6719 - val_mae: 50217.6719
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 49571.0938 - mae: 49571.0938 - val_loss: 50224.9570 - val_mae: 50224.9570
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49558.2734 - mae: 49558.2734 - val_loss: 50229.4531 - val_mae: 50229.4531
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49552.6875 - mae: 49552.6875 - val_loss: 50228.6484 - val_mae: 50228.6484
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 49545.6016 - mae: 49545.6016 - val_loss: 50233.6094 - val_mae: 50233.6094
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49537.4375 - mae: 49537.4375 - val_loss: 50245.0078 - val_mae: 50245.0078
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49525.1289 - mae: 49525.1289 - val_loss: 50240.8672 - val_mae: 50240.8672
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49520.1602 - mae: 49520.1602 - val_loss: 50250.0859 - val_mae: 50250.0859
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49512.2422 - mae: 49512.2422 - val_loss: 50236.3945 - val_mae: 50236.3945

In [21]:
# Load Tensorborad Extension
%load_ext tensorboard

In [23]:
%tensorboard --logdir regression/fit20250501-012305

Reusing TensorBoard on port 6006 (pid 18912), started 0:00:08 ago. (Use '!kill 18912' to kill it.)

In [24]:
# Evaluate model on the test data
test_loss, test_mae = model.evaluate(x_test, y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 2ms/step - loss: 50211.8828 - mae: 50211.8828
Test MAE : 50211.8828125

In [25]:
model.save('regression_model.h5')

d:\Udemy\Gen AI\Projects\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(